# Generated by Django 5.2 on 2025-06-20 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_choice', models.CharField(max_length=100)),
                ('favorite_color', models.CharField(max_length=50)),
                ('cleanliness', models.CharField(max_length=50)),
                ('sleep_schedule', models.CharField(max_length=50)),
                ('noise_level', models.CharField(max_length=50)),
                ('study_preference', models.CharField(max_length=50)),
                ('health_issues', models.TextField(blank=True, null=True)),
                ('religion', models.CharField(max_length=100)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
